duplicatesinarray.cpp
Saikat2407/DSA_Hacktoberfest pull request #76
Opened 2022-10-16 14:58 UTC by Abulaman23

Thanks for reading my pull request!!

2022-10-16 15:24 UTC, Saikat2407 commented on Leetcode/duplicatesinarray.cpp
> +#include<bits/stdc++.h>
first line should be problem link in comments

2022-10-16 15:25 UTC, Saikat2407 requested changes
1. add the problem link on top of the file
2. delete the exe file

2022-10-16 15:43 UTC, Abulaman23 commented
Did the changes,Kindly look into it.

2022-10-16 16:58 UTC, Saikat2407 commented on Leetcode/duplicatesinarray.cpp
> -
Add the main fuction

2022-10-16 16:59 UTC, Saikat2407 requested changes

2022-10-16 16:59 UTC, Saikat2407 commented on Leetcode/duplicatesinarray.cpp
> +};
1. remove ";" from line 17

2022-10-17 02:41 UTC, Abulaman23 commented
Changes done,do look into it!

2022-10-17 04:35 UTC, Saikat2407 approved these changes
**Approved**

2022-10-17 04:35 UTC, merged